### PR TITLE
Use cache to speed up CI

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
I originally planned to speed up CI execution time to about 1/4 by passing the cache option to textlint and caching them, but the current CI is a little bit more special, so it can't be much faster.

**Comment by imbsky** [comment]
textlint is a relatively slow tool, so I'm interested in keeping CI simple without using reviewdog and using cache to speed it up.

**Comment by uetchy** [comment]
@imbsky is this staled?

**Comment by imbsky** [comment]
@Naturalclar @uetchy Rebased!

**Pull request merged**
