### PR TITLE
いくつかの修正を行いました (Did some corrections in contributing/how-to-file-an-issue.md)

### PR DESCRIPTION
**Pull request by prateekpardeshi**
## チェックリスト

- [x] [翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md) に目を通しました。
- [x] [Translation Guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) に目を通しました。
- [x] `textlint` を使って校正を行いました。
- [x] 文章全体を最初から読み直して不自然な箇所が無いことを確認しました。
- [x] `Allow edits from maintainers` にチェックを入れました。

> しばらく待ってもレビューが終わらなかったり、必要なレビュー数に足りない状態が続いた場合は、[こちら](https://github.com/gatsbyjs/gatsby-ja/issues/1)からメンテナーを探して、@を付けてメンションを飛ばしてください。

## 補足

Ref: #1

### CODE REVIEW

**Comment by prateekpardeshi** [comment]
@hirotaka  @imbsky  @Naturalclar @uetchy  Anyone free?

**Comment by imbsky** [comment]
It has only been 6 hours since you opened this PR. Do NOT ping at short intervals. First, fix all issues as the CI warns you. We will review this PR after that is completed.

**Comment by imbsky** [comment]
and @uetchy said in the previous PR you opened as follows.
"Do not use neural machine translation directly. Please refer to the Translation Style Guide and make any necessary fixes."
But the content of PR is the same as before.

**Comment by imbsky** [comment]
Even if this is not a neural machine translation, at least all the issues that CI warns of should be fixed.

**Comment by prateekpardeshi** [comment]
Warns have been fixed! 🙂

**Comment by uetchy** [comment]
Errors still persist. Check [errors in diff](https://github.com/gatsbyjs/gatsby-ja/pull/169/files) and fix them.
If you are not familiar with Markdown, check [this](https://guides.github.com/features/mastering-markdown/) out.

As many parts of the translation are incomprehensible, we recommend you rewrite your translation from one that is not based on machine translation.

**Comment by prateekpardeshi** [comment]
Cleared all Markdown errors

**Comment by imbsky** [comment]
There are some things that I should confirm with you.

- Did you use machine translation?
  - Depending on the service used, we can't merge this due to the terms of service. Also, if you tell a lie and merge this, and found after many other people have made changes, we need to redo all the translations.
- Have you read the our style guide?
  - This is a important thing you can do with the least effort.

**Comment by imbsky** [comment]
Many OSS maintainers, not just this project, review PR in a really limited amount of time. So please note that although we can review the translation, we can't correct and/or teach the Japanese itself.

**Comment by uetchy** [comment]
@prateekpardeshi What happened to this PR? Just want to know if you want to continue working on this page.

**Comment by prateekpardeshi** [comment]
No, I'm tired after spending a lot of time on corrections and still achieving nothing 😭

**Pull request closed without merging**
